name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build build fedora30
      run: docker build . --file fedora30 --tag myfedora30:latest
    - name: Build the Docker image fedora31
      run: docker build . --file fedora31 --tag myfedora31:latest
    - name: Build the Docker image centos7
      run: docker build . --file centos7 --tag mycentos7:latest
    - name: Build centos8 
      run: docker build . --file centos7 --tag mycentos8:latest

